services:
  database:
    image: mysql:8.4.0
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: 'starterKit'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - starterKit:/var/lib/mysql
    networks:
      - app_network
networks:
    app_network:
      driver: bridge
volumes:  
  starterKit:    